#!/usr/bin/env bash
#
# backport-sync.sh — merge the main game (Unity 6.6) into this Unity 6.3 LTS
# backport branch, auto-resolving everything that is pure editor churn.
#
# The backport branch deliberately diverges from upstream in a handful of places
# because 6.3 lacks APIs that 6.6 has, or vice versa. Most of the divergent
# files are not authored content at all: Unity rewrites them every time the
# project is opened, so they conflict on every merge and then re-dirty the tree
# immediately afterwards. Those are reverted to "ours" automatically, which is
# correct — the local copy is always the one matching the 6.3 editor.
#
# Files that encode real intent are never auto-resolved. They are listed at the
# end of every run so a human can look at them.
#
# See AGENTS.md for the background on why this branch exists.

set -euo pipefail

# ---------------------------------------------------------------- constants --

# Upstream is the Open Frontier project. This is a standalone repo (it used to
# be a worktree of the Frontier checkout, which meant remotes were SHARED and a
# bare `git push origin` from here would have pushed the backport branch to the
# Frontier repo). It is now independent, with:
#   origin   -> SolacianAllie/InterstellarPilot-OpenBackport   (this project)
#   frontier -> SolacianAllie/InterstellarPilot-OpenFrontier   (upstream)
readonly BRANCH="Backport"
# Merge from frontier/Legacy, NOT frontier/Dev.
#
# Legacy is the default branch of the Open Frontier repo and is the one the
# release-facing work lands on — the licensing set, README, trademark policy.
# Dev is the working branch that feeds Legacy by pull request, so it is a strict
# subset: at time of writing Legacy was 11 commits AHEAD of Dev and 0 behind.
# Syncing from Dev therefore silently misses merged work, which already happened
# once — the revised Linux Foundation CLA was missed entirely because it had
# landed on Legacy. Syncing from Legacy is a strict superset and is what you want
# for a branch that ships.
#
# If you specifically want work that is still sitting on Dev unmerged, pass it
# explicitly: tools/backport-sync.sh frontier/Dev
readonly SOURCE_DEFAULT="frontier/Legacy"

# URP 17.3 (Unity 6.3) ships k_LastVersion = 10. URP 17.6 (Unity 6.6) ships 11.
# A merge from upstream can reintroduce 11, which compiles fine and then throws in
# URPBuildDataValidator at the start of every build. Nothing but URP's own
# upward-only version bump ever writes this field, so it must be re-asserted.
readonly URP_LAST_VERSION="10"
readonly URP_GLOBAL_SETTINGS="Assets/UniversalRenderPipelineGlobalSettings.asset"

# Editor-owned / machine-owned: reverted to ours on every sync.
# Nothing here is authored by hand.
readonly AUTO_OURS_EXACT=(
  "ProjectSettings/ProjectVersion.txt"          # engine pin — must never drift
  "Packages/packages-lock.json"                 # regenerated by Package Manager
  "ProjectSettings/PackageManagerSettings.asset"
  "ProjectSettings/GraphicsSettings.asset"
  "Assets/Settings/OpenFrontier-URP.asset"
)

# Editor-generated per-scene output. Matched by `find`, not shell globs: these
# live at arbitrary depth under Assets/Scenes (e.g.
# Scenes/ui/menu/LandingScene/ReflectionProbe-0.exr), so a `Scenes/*/name`
# glob silently misses all but the shallowest ones — and silently missing a
# conflicted path means the merge stalls instead of auto-resolving.
readonly AUTO_OURS_NAMES=(
  "LightingData.asset"
  "LightingData.asset.meta"
  "ReflectionProbe-*.exr"
  "ReflectionProbe-*.exr.meta"
)
readonly AUTO_OURS_SCAN_ROOT="Assets/Scenes"

# ------------------------------------------------------------------- helpers --

if [ -t 1 ]; then
  BOLD=$'\033[1m'; RED=$'\033[31m'; GREEN=$'\033[32m'
  YELLOW=$'\033[33m'; BLUE=$'\033[34m'; DIM=$'\033[2m'; RESET=$'\033[0m'
else
  BOLD=""; RED=""; GREEN=""; YELLOW=""; BLUE=""; DIM=""; RESET=""
fi

section() { printf '\n%s== %s ==%s\n' "$BOLD" "$1" "$RESET"; }
info()    { printf '   %s\n' "$1"; }
ok()      { printf '   %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
warn()    { printf '   %s!%s %s\n' "$YELLOW" "$RESET" "$1"; }
fail()    { printf '   %sx%s %s\n' "$RED" "$RESET" "$1"; }
die()     { printf '\n%serror:%s %s\n' "$RED" "$RESET" "$1" >&2; exit 1; }

usage() {
  cat <<'EOF'
backport-sync.sh — merge Open Frontier (Legacy) into the Unity 6.3 LTS backport branch

USAGE
  tools/backport-sync.sh [options] [source]

  source            branch/ref to merge from (default: frontier/Legacy)

OPTIONS
  --dry-run         report what would change; touch nothing
  --no-commit       leave the merge staged for manual inspection
  --verify          run the invariant checks and exit (no merge)
  --abort           roll back an in-progress or last sync
  -h, --help        show this help

REPOSITORIES
  origin    SolacianAllie/InterstellarPilot-OpenBackport   (this project)
  frontier  SolacianAllie/InterstellarPilot-OpenFrontier   (upstream)
            Merges frontier/Legacy, the default branch and a strict superset
            of frontier/Dev. Pass frontier/Dev explicitly for unmerged work.

TYPICAL USE
  tools/backport-sync.sh --dry-run     # see what a sync would do
  tools/backport-sync.sh               # merge, auto-resolve, commit
  # reopen the project in 6.3, read Logs/Editor.log, then build

NOTES
  * The project must be CLOSED in the editor; this script refuses to run
    against a live editor because a sync underneath one corrupts the import.
  * A clean compile proves nothing here. This branch has shipped two
    build-only failures (URP global-settings version, TMP prebuild atlas
    reference). Always build before you call a sync good.
EOF
}

# ---------------------------------------------------------------- preflight --

preflight() {
  section "Preflight"

  local root
  root="$(git rev-parse --show-toplevel)"
  info "repo $root"

  # Refuse to run inside a merge we previously abandoned.
  if [ -f "$root/.git/MERGE_HEAD" ] || [ -f "$(git rev-parse --git-path MERGE_HEAD)" ]; then
    die "a merge is already in progress. Finish it, or run: $0 --abort"
  fi

  local branch
  branch="$(git branch --show-current)"
  [ "$branch" = "$BRANCH" ] || die "on '$branch', expected '$BRANCH'"
  ok "on $BRANCH"

  # A live editor will happily overwrite anything we just merged.
  if [ -e "$root/Temp/UnityLockfile" ]; then
    die "the editor has this project open (Temp/UnityLockfile exists).
      Close Unity, then re-run. Merging under a running editor corrupts the import."
  fi
  ok "editor is closed"

  if [ -n "$(git status --porcelain)" ]; then
    printf '\n'
    warn "working tree is not clean:"
    git status --short | sed 's/^/     /'
    die "commit or stash these first — a sync needs a known starting point"
  fi
  ok "working tree clean"
}

# ------------------------------------------------------------- merge + fixup --

# Force a set of paths back to our side of the merge.
#
# Works for both conflicted and cleanly-merged paths: HEAD is still the
# pre-merge commit while a --no-commit merge is staged, so "ours" is HEAD
# either way.
resolve_ours() {
  local -a paths=("$@")
  [ "${#paths[@]}" -gt 0 ] || return 0

  local p
  for p in "${paths[@]}"; do
    # Already identical to our side? Nothing to do.
    if git diff --quiet HEAD -- "$p" 2>/dev/null; then
      continue
    fi
    git checkout HEAD -- "$p"
    git add -- "$p"
    printf '     reverted to 6.3: %s\n' "$p"
  done
}

# Echo every editor-owned path that exists, at any depth.
# Uses find(1), not shell globbing: `Assets/Scenes/*/name` matches exactly one
# directory level and would skip Scenes/ui/menu/<Scene>/... entirely.
list_editor_owned() {
  local n
  for n in "${AUTO_OURS_NAMES[@]}"; do
    find "$AUTO_OURS_SCAN_ROOT" -type f -name "$n" 2>/dev/null
  done | sort -u
}

collect_auto_ours() {
  local p
  for p in "${AUTO_OURS_EXACT[@]}"; do
    printf '%s\n' "$p"
  done
  list_editor_owned
}

check_urp_version() {
  # Read-only. Returns 1 if the version is wrong. Must never write.
  local file="$URP_GLOBAL_SETTINGS"
  local want="$URP_LAST_VERSION"

  if [ ! -f "$file" ]; then
    warn "$file missing — Unity will regenerate it on next open"
    return 0
  fi

  local count
  count="$(grep -c '^[[:space:]]*m_AssetVersion:' "$file" || true)"
  if [ "$count" != "1" ]; then
    fail "$file has $count m_AssetVersion fields (expected 1)"
    return 1
  fi

  if grep -qE "^[[:space:]]*m_AssetVersion:[[:space:]]*$want[[:space:]]*$" "$file"; then
    ok "m_AssetVersion is $want"
    return 0
  fi

  local have
  have="$(grep -oE '^[[:space:]]*m_AssetVersion:[[:space:]]*[0-9]+' "$file" | grep -oE '[0-9]+$')"
  fail "m_AssetVersion is '$have', expected '$want' — URPBuildDataValidator throws at build start"
  return 1
}

repair_urp_version() {
  # Write path, used only during a sync. A merge from upstream can reintroduce 11,
  # and nothing but URP's own upward-only version bump ever corrects it.
  #
  # If the file is conflicted we resolve it to our side first: our copy is the
  # one Unity already re-serialized with 17.3's schema, so it is the only
  # coherent one here. It stays in the human-review queue afterwards, because
  # shader-stripping settings are a real tuning knob and Dev may have changed
  # them.
  local file="$URP_GLOBAL_SETTINGS"
  local want="$URP_LAST_VERSION"

  [ -f "$file" ] || { warn "$file missing"; return 0; }

  if git ls-files -u -- "$file" | grep -q .; then
    resolve_ours "$file"
    info "resolved conflict in $file to our side (only coherent under 6.3)"
  fi

  local count
  count="$(grep -c '^[[:space:]]*m_AssetVersion:' "$file" || true)"
  if [ "$count" != "1" ]; then
    fail "$file has $count m_AssetVersion fields (expected 1) — not touching it"
    return 1
  fi

  if grep -qE "^[[:space:]]*m_AssetVersion:[[:space:]]*$want[[:space:]]*$" "$file"; then
    ok "m_AssetVersion already $want"
    return 0
  fi

  local have
  have="$(grep -oE '^[[:space:]]*m_AssetVersion:[[:space:]]*[0-9]+' "$file" | grep -oE '[0-9]+$')"
  sed -i -E "s/^([[:space:]]*m_AssetVersion:[[:space:]]*)[0-9]+[[:space:]]*$/\\1$want/" "$file"
  git add -- "$file"
  warn "re-asserted m_AssetVersion: $have -> $want"
}

assert_project_version() {
  local want_major="6000.3"
  local got
  got="$(grep -m1 '^m_EditorVersion:' ProjectSettings/ProjectVersion.txt 2>/dev/null | awk '{print $2}' || true)"
  if [ -z "$got" ]; then
    fail "could not read ProjectSettings/ProjectVersion.txt"
    return 1
  fi
  case "$got" in
    "$want_major"*) ok "editor pin $got" ;;
    *) fail "editor pin is '$got', expected $want_major.*" ; return 1 ;;
  esac
}

assert_package_pins() {
  local bad=0
  local pair
  # package:expected-version
  for pair in \
    "com.unity.render-pipelines.universal:17.3.0" \
    "com.unity.ugui:2.0.0"
  do
    local pkg="${pair%%:*}" want="${pair##*:}"
    local have
    have="$(python3 -c "
import json,sys
try:
    d=json.load(open('Packages/manifest.json'))['dependencies']
    print(d.get('$pkg','<missing>'))
except Exception:
    print('<unreadable>')
" 2>/dev/null)"
    if [ "$have" = "$want" ]; then
      ok "$pkg $have"
    else
      fail "$pkg is '$have', expected '$want'  (manifest.json needs a human merge)"
      bad=1
    fi
  done
  return $bad
}

verify() {
  section "Invariants"
  local rc=0
  assert_project_version || rc=1
  check_urp_version     || rc=1
  assert_package_pins   || rc=1
  return $rc
}

report_review_queue() {
  section "Needs a human"
  local f
  for f in \
    "Packages/manifest.json" \
    "ProjectSettings/ProjectSettings.asset" \
    "Assets/Scripts/Assembly-CSharp/UnityEngine.UI/AbstractFlowLayoutGroup.cs" \
    "Assets/Scripts/UnityUIExtensions/UnityEngine.UI.Extensions/FlowLayoutGroup.cs" \
    "$URP_GLOBAL_SETTINGS"
  do
    if git diff --quiet HEAD -- "$f" 2>/dev/null; then
      info "$DIM$f  (unchanged by this sync)$RESET"
    else
      printf '   %s* %s%s\n' "$YELLOW" "$f" "$RESET"
    fi
  done
  printf '\n'
  info "${YELLOW}manifest.json and ProjectSettings.asset carry real Dev changes"
  info "when they conflict — take Dev's additions but keep our pins"
  info "(URP 17.3, ugui 2.0, minSdk 25).$RESET"
}

# --------------------------------------------------------------------- main --

main() {
  local source="$SOURCE_DEFAULT" dry=0 commit=1 do_verify=0 do_abort=0

  while [ $# -gt 0 ]; do
    case "$1" in
      --dry-run)    dry=1 ;;
      --no-commit)  commit=0 ;;
      --verify)     do_verify=1 ;;
      --abort)      do_abort=1 ;;
      -h|--help)    usage; exit 0 ;;
      -*)           die "unknown option: $1 (try --help)" ;;
      *)            source="$1" ;;
    esac
    shift
  done

  cd "$(git rev-parse --show-toplevel)"

  if [ "$do_abort" -eq 1 ]; then
    section "Abort"
    git merge --abort 2>/dev/null && info "merge aborted" || info "no merge in progress"
    git reset --hard HEAD >/dev/null 2>&1 || true
    info "working tree reset to $(git rev-parse --short HEAD)"
    exit 0
  fi

  if [ "$do_verify" -eq 1 ]; then
    verify || exit 1
    printf '\n%sAll invariants hold.%s\n' "$GREEN" "$RESET"
    exit 0
  fi

  preflight

  section "Source"
  git rev-parse --verify "$source" >/dev/null 2>&1 || die "no such ref: '$source'"
  if git rev-parse --verify "origin/$source" >/dev/null 2>&1; then
    ok "origin/$source $(git rev-parse --short "origin/$source")"
  fi
  ok "merging $source $(git rev-parse --short "$source")"

  if [ "$(git rev-parse "$source")" = "$(git rev-parse HEAD)" ]; then
    printf '\n%sAlready up to date with %s.%s\n' "$GREEN" "$source" "$RESET"
    exit 0
  fi

  # Remember where we were, so --abort can always get back.
  local rollback
  rollback="$(git rev-parse HEAD)"
  printf '\n%srollback: git reset --hard %s%s\n' "$DIM" "$rollback" "$RESET"

  if [ "$dry" -eq 1 ]; then
    section "Dry run"
    git log --oneline HEAD.."$source" | sed 's/^/   /' | head -40
    local n
    n="$(git rev-list --count HEAD.."$source")"
    printf '\n   %s commit(s) incoming%s\n' "$n" "$RESET"
    printf '   would merge, auto-revert %d editor-owned path(s), re-assert URP version\n' \
      "$(collect_auto_ours | wc -l)"
    printf '\n%sNo changes made.%s\n' "$DIM" "$RESET"
    exit 0
  fi

  section "Merging"
  # --no-commit so we can fix things up before the commit lands.
  # Conflicts are expected and handled below, so don't let it bail.
  if git merge --no-commit --no-ff "$source" >/dev/null 2>&1; then
    ok "merged cleanly"
  else
    warn "merge reported conflicts — resolving"
  fi

  section "Auto-resolving editor-owned files"
  local -a ours=()
  while IFS= read -r p; do
    [ -n "$p" ] && ours+=("$p")
  done < <(collect_auto_ours)
  resolve_ours "${ours[@]}"
  ok "considered ${#ours[@]} editor-owned path(s)"

  section "URP global settings"
  repair_urp_version || true

  section "Invariants"
  assert_project_version || true
  assert_package_pins   || true

  report_review_queue

  if [ "$commit" -eq 1 ]; then
    section "Committing"
    local conflicts
    conflicts="$(git diff --name-only --diff-filter=U)"
    if [ -n "$conflicts" ]; then
      printf '%s\n' "$conflicts" | sed 's/^/   unresolved: /'
      die "unresolved conflicts remain — resolve them, then git commit"
    fi
    git commit -q -F - <<EOF
Merge $source into $BRANCH (Unity 6.3 LTS backport)

Auto-synced by tools/backport-sync.sh. Editor-owned files (ProjectVersion,
packages-lock, PackageManagerSettings, GraphicsSettings, the URP pipeline asset,
per-scene LightingData and ReflectionProbe output) are reverted to the 6.3 side
because Unity rewrites them on every open and 6.6's serialization is unreadable
here. m_AssetVersion on the URP global settings is re-asserted to $URP_LAST_VERSION
(URP 17.3 k_LastVersion); a merge from $source can silently reintroduce 11, which
compiles but fails every build in URPBuildDataValidator.

NOT verified by this commit — reopen in 6.3, read Logs/Editor.log, and build.
EOF
    ok "committed $(git rev-parse --short HEAD)"
  else
    section "Left staged (--no-commit)"
    info "inspect with: git diff --cached --stat"
  fi

  printf '\n%sNext:%s close/reopen the project in 6.3, check Logs/Editor.log for\n' "$BOLD" "$RESET"
  info "'error CS', then BUILD. This branch has produced two build-only"
  info "failures that compiled cleanly."
  printf '\n%sRollback:%s git reset --hard %s\n' "$DIM" "$RESET" "$rollback"
}

main "$@"
